travis:
  secure:
    BINSTAR_TOKEN: FeFXI10DGnyuSVzB5S7+7Un0fx6ciYhjUam7Sm72vb5otcavb2xJDP2K+rKR6ipX2/xK6v2yqXCnqXN/YgiE9yh4uA2Ff61a+/WvgG/tM1yAmGpR8wDwg3GI4SsZHJWDeTuPPGj6lyLhNE9+Krdjy0r1YxnkjUgTbfuLLsYttHOqL/76q+2s5u3PdPtRW9HPU/WoFzc7krlBUYyg9fzfeIBCJ13QFgzQD6iSR8c/Hje4v/0S4U0Gf7yTQIeyAdieKZ5Hq9+9jn4n9nVSIN/ru9venddue++rIY/Ug/Nb5mwmVshLbWXG/J2s2CXuAUKabrrK01F2FvXuhgwMPRsIOF7uRv7yqrIH5w9AluUsdxwXN8+u11yNyMvJBsbp6KuI0wfkhw8kDQ03cFWTTWMF7FvGmk1VBFOZZEM39nRGJS/P5c7c/lzYBtURb8hbTytH8E2oDrtgML4nz7JaH7IczFZ5Q6XItL7R2FKv7I8j2I1v6bRja5mpDqUgSZjrxEWtGKCTtoKb/97Q1q03NZbwk6a8BQwyk4CmTnk694grLqLuCJjStjpf3Ev6uoNPJt4coJ0hx7SV0PwSIXsCE0mTWQZoRubfpzUVPhWxLJObmXdMmLK5P3zH8t3OXvD6+p3yXTVlhW38mJIYlv+U4J6zfu1pbOfcCw4Vf7lOt1SHXxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
