appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: bDqrpnH0wgzpeXZ332cua8JG9AZrmJsDDD1BGOJCJor+FLe9VsyHHyQ+rweAZ2j0xWjJ0ZUU/TQ5xhlnfYt5wko+/ShbFlpkvHMccjXDbA+4kw29nGi3glS6FQGdNgRmym09KsgXbv1qTOamoogxTosugmGVweJyV08J8J4doLHTAnoHxzdIXkn75G73NaJ3oJ4dr9lBlshdHnvGUE4YBIadSWs8PMBiDp4oQO8hGU/5WgBxLW82zJqc5YlLbwcU+tgXJdKqVfJkw9v8Dw5nmeTFMIcA8lgoaHVS44mfSmJMITdr+mJTu4oxoCz0jR96zdI+k2KL1vqw9K0K3uPpAwgBriZaewfdpNxBcmyckYocHl1HCLkmh91PQhxbsSjx/cZy2jDY5SJJbVW5uCjLxt39n4FHBtNL1RdTqSy5+wigLRkhc8eKXo5NPO8POuPue0tTYdiDwJrnGA1S6GArnH/DHfVBo0ITJ7vFMrMZv3jE0+FDqAj328e9TyGPmiySUsYS1NQ5t1DIT2CNDn1cNKzaamC6cB1ty9niWxtR5RmTmYBPtduDmrhv7V6fYwWd7mK+aB/zlRQviW9nddPz/EBEdaAP/+36DawYoQI/giW/JMzGOOzbLjSWZbWSR6qta3srF8DSInWhf7KoDPi3e4xR3S76CUKIakbVV44+Sdo=
conda_forge_output_validation: true
