travis:
  secure:
    BINSTAR_TOKEN: gMJYMWYTVuoGp/5nQkVus2edb5VlqT1JUltqtpFIuubyOATLNE89y6ZQHHonlCJ5shrVkKT01WwALA7vWwRt98x2cDd+p91RMCZgLd+1qAq99x69cWt+AgIHUpDLHXdRMLa3BnwD3Qs/gLhXX4f9QCHlT69MVKwNPfUpjIzX61qnzjESsXdYQLEwak29h40TI2TtYuKNE0/oHpRO4ibndLu00bJOQFocyJdeuwmQFZ3SHgN1/qHbDoZV912hYA49XF65Ba1iZfqT9HrBfeZ9yxxXajRh7v0NgUakmBtzJupZcEO3mSDxjmhRMhVUzpzi1MbWlFqgHQD+x9AcvTEAWqVMVBRvsmogbfuKoMO8RtffKyOWDxf2KXluhFX5dhWofxaCjZZwFsX/MQsKMQaPFQrS9XPLxvL/5QpZqVXi49vhLbGwn48nY3w8gPobp/zt898RPuRlopTOakfTZDCNviP/ieGBkPKmdh65BJuTlKJVJ0iQe6LQCg87ZxS1bVSkwBc2ED/nEOghNY8w64T9dz3gC5lq5i+ICQyJMUxYPhjrZgWsR/xXpDLEY/BMKBluOQ9LeN6pgOdmKDBUrwdU/d4/TlQmMgahDqW5ETGBv2MYQDPhWr0VRVB8Y6Xexp3KYQyE1vga6TfBCUbkLsT8Rr4SCJFG8FIVJsdAQ4Tc1hY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
